### ISSUE TITLE
Tasks Checklist.

### ISSUE THREAD

**Issue by sidntrivedi** [rapport4/TutOverflow#1]
- [x]  1. Decide the functionality of the platform.

- [x]  2. Bring out a basic ER model/DB structure.

- [x] 2.1 Make sure to apply the normalization concepts to the database

- [x] 3. Confirm the functioning of backend and database part.

- [x]  4. Make a basic frontend and then, implement the SQL queries and PHP script i.e. the Course part and the blog part.

- [x] 4.1 Learn about building a voting app in PHP

- [x] 4.2 Learn about building a blog in PHP

- [x] 5. Beautify the frontend.

- [x] 6. Implement the Chart.js and other API parts of the project.

- [ ] 7. Host the site on Heroku/GH pages/infinity host.

- [ ] 8. Optimize the site if possible.

**Do add any necessary tasks if I missed any.**

**Comment by bymayanksingh** [comment]
Will take a close look and discuss the plans on coming Saturday, Sunday.

**Comment by bymayanksingh** [comment]
Added, Basic Database Structure. @sidntrivedi012  PTAL.

**Comment by bymayanksingh** [comment]
I am championing work on the POLL (Trend Analysis) part of TutOverflow

**Comment by sidntrivedi** [comment]
So, we have 4 pages more left to be championed.
1. Login/Signup Page
2. Blog
3. Courses Page
5. Add Tutorial Page.

I would like to take the Courses Page. 
@araushan has agreed to take up Login/Signup. @nightwarrior-xxx Your call ? Would blog be fine? Though, when needed we can contribute to other's initiative too.

**Comment by nightwarriorftw** [comment]
Yeah,I will be doing blog part.But I need a revision first (css,bootstrap,jquey) .I will finish revision before monday and then till Wednesday I will try to complete the blog part .
Is that ok @sidntrivedi012 ?

**Comment by bymayanksingh** [comment]
I guess that will work @nightwarrior-xxx

**Comment by sidntrivedi** [comment]
Yes @nightwarrior-xxx . You can even do that after T2. I think we will be getting more free time to work on it after the exams.

**Comment by nightwarriorftw** [comment]
But what about Mid Term Evaluation .I guess we have enough to show for that.

**Comment by sidntrivedi** [comment]
@nightwarrior-xxx We have done enough work to make up for the Mid eval.

**Comment by nightwarriorftw** [comment]
We or you three .Because I have done nothing.

**Comment by sidntrivedi** [comment]
@nightwarrior-xxx No, by 'we' I mean our group i.e. we atleast have the DB tables and some front end ready to save our back. I think the main thing we should get done before T2 is the ER model/the functioning of the platform. The coding part we can even do after T2.

**Comment by nightwarriorftw** [comment]
@sidntrivedi012 We can use draw.io to draw ER model online.It will also help us in how to make ER model online.

**Comment by sidntrivedi** [comment]
@nightwarrior-xxx Awesome. But,first we will have to do a lot of hand work and brainstorming.

**Comment by nightwarriorftw** [comment]
@sidntrivedi012 Nothing in the world is easy.```We are just confined by the walls we built for our-self```

**Comment by bymayanksingh** [comment]
Added files for Trend Analysis

**Comment by bymayanksingh** [comment]
Commendable Work @sidntrivedi012 @nightwarrior-xxx @araushan :)

**Comment by sidntrivedi** [comment]
Closing this for now. The project has to be made responsive and then hosted.
